[package]
name = "mockalloc"
version = "0.1.0"
authors = ["Diggory Blake <diggsey@googlemail.com>"]
edition = "2018"

[workspace]
members = ["mockalloc-macros"]

[lib]


[dependencies]
mockalloc-macros = { version = "0.1.0", path = "mockalloc-macros" }
